import { api } from './api';

// App-wide print/PDF utility. Any report can print with the same definable
// letterhead (organisation name, address, logo) and orientation.

export type Orientation = 'portrait' | 'landscape';
export interface PrintHeader { org_name: string; org_address: string; logo_url: string; }

let _hdr: Promise<PrintHeader> | null = null;
export function loadPrintHeader(force = false): Promise<PrintHeader> {
  if (!_hdr || force) {
    _hdr = api.getPrintHeader()
      .then((h: any) => ({ org_name: h.org_name || '', org_address: h.org_address || '', logo_url: h.logo_url || '' }))
      .catch(() => ({ org_name: '', org_address: '', logo_url: '' }));
  }
  return _hdr;
}
export function invalidatePrintHeader() { _hdr = null; }

function esc(s: string) {
  return (s || '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
}

function letterhead(h: PrintHeader, title: string, meta?: string) {
  return `<div class="ni-print-hdr">
    <div class="ni-print-left">
      ${h.logo_url ? `<img src="${esc(h.logo_url)}" class="ni-print-logo"/>` : ''}
      <div class="ni-print-org">${esc(h.org_name || '')}</div>
      <div class="ni-print-addr">${esc(h.org_address || '')}</div>
    </div>
    <div class="ni-print-right">
      <div class="ni-print-title">${esc(title)}</div>
      ${meta ? `<div class="ni-print-meta">${esc(meta)}</div>` : ''}
      <div class="ni-print-meta">${new Date().toLocaleString()}</div>
    </div>
  </div>`;
}

const BASE_CSS = (o: Orientation) => `
  @page { size: A4 ${o}; margin: 12mm; }
  * { box-sizing: border-box; }
  body { font-family: Arial, "Segoe UI", sans-serif; color:#222; margin:0; }
  .ni-print-hdr { display:flex; justify-content:space-between; align-items:flex-start; width:100%;
                  border-bottom:2px solid #333; padding-bottom:10px; margin-bottom:12px; gap:20px; }
  .ni-print-logo { height:46px; margin-bottom:6px; display:block; }
  .ni-print-org { font-size:18px; font-weight:700; }
  .ni-print-addr { font-size:11px; color:#555; white-space:pre-line; }
  .ni-print-right { text-align:right; font-size:11px; }
  .ni-print-title { font-size:15px; font-weight:700; margin-bottom:4px; }
  .ni-print-foot { margin-top:18px; font-size:10px; color:#888; }
  .no-print { display:none !important; }
  table { border-collapse:collapse; }
  .ni-print-body table { width:100%; font-size:11px; }
  .ni-print-body th { border-bottom:2px solid #333; padding:5px 6px; text-align:left; }
  .ni-print-body td { border-bottom:1px solid #ddd; padding:4px 6px; }
`;

function open(docHtml: string) {
  const w = window.open('', '_blank');
  if (!w) { alert('Allow pop-ups to print.'); return; }
  w.document.write(docHtml);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}

/** Print custom HTML (e.g. a hand-built statement). */
export async function printHtml(opts: { title: string; orientation?: Orientation; bodyHtml: string; meta?: string }) {
  const h = await loadPrintHeader();
  const o = opts.orientation || 'portrait';
  open(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(opts.title)}</title>
    <style>${BASE_CSS(o)}</style></head><body>
    ${letterhead(h, opts.title, opts.meta)}
    <div class="ni-print-body">${opts.bodyHtml}</div>
    <div class="ni-print-foot">Generated by Neotec Insight</div>
    </body></html>`);
}

/** Print an on-screen element, carrying the app's stylesheets for fidelity. */
export async function printElement(el: HTMLElement | null, opts: { title: string; orientation?: Orientation; meta?: string }) {
  if (!el) return;
  const h = await loadPrintHeader();
  const o = opts.orientation || 'portrait';
  const styles = Array.from(document.querySelectorAll('link[rel="stylesheet"], style'))
    .map((n) => n.outerHTML).join('\n');
  open(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(opts.title)}</title>
    ${styles}<style>${BASE_CSS(o)}</style></head><body>
    ${letterhead(h, opts.title, opts.meta)}
    <div class="ni-print-body">${el.outerHTML}</div>
    <div class="ni-print-foot">Generated by Neotec Insight</div>
    </body></html>`);
}
